apiVersion: 1

datasources:
  - name: Mantenedor DB
    type: postgres
    url: db_mantenedor:5432
    database: db_mantenedor
    user: postgres
    secureJsonData:
      password: password123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: false
    editable: true
    access: proxy
